sudo: required
language: Java
jdk: oraclejdk8
env:
  global:
    - secure: "sG5h/UB/s3uhN6DF4F4jRHLKDTbqGipDdCBaUu/8mZ8kqgtZtMAh6yodj1HrRbEzov0kCsjDYTnv90YzZWIbmrzRNY3M/B/P47DKkCxjf6ejbSY9D0OJnqbjzOyfiDP6bAs64pUzfjylkYuvNVhkCxN0Ay7k8cvT9D0XOX3nUHc="
    - secure: "P5oMhssZHp8eBezF2WEUZrzR6du/ibhcNRmZhSC8uKN0NO6AKlGLBID2llQrWED7RoZLoYhReR04LqdQZboGKvmqZ1TRHDkhwUOsFAGFIC2wxFrZPNy06anOjaT+ZfOsMZCtN+mXCaCARSBCSJP7L0vyEIdfaw+ZG2LxBV2GrK0="
before_install: certificates/add-to-cacerts.sh
install: mvn install -DskipTests -DskipITs -q 
script:
  - >
    if [ ${TRAVIS_BRANCH} == "develop" ]; then
    mvn clean verify -Psonar && mvn cobertura:cobertura-integration-test coveralls:report;
    else
    mvn clean verify && mvn cobertura:cobertura-integration-test coveralls:report;
    fi;
# Run Sonar analysis only after a successful build to avoid incomplete results
after_success:
  - >
    if [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ ${TRAVIS_BRANCH} == "develop" ]; then
    mvn sonar:sonar -Dsonar.host.url=https://repository.kaazing.com/secret-sauce/sonarqube -Dsonar.login=${SONAR_USER} -Dsonar.password=${SONAR_PASSWORD};
    else
    echo "SonarQube analysis is performed only for commits on the develop branch(not for PRs)";
    fi;
