language: Java
jdk:
  - oraclejdk7
  - openjdk7
install: mvn clean -DskipTests -DskipITs install
script: mvn clean verify
after_success:
  - mvn clean cobertura:cobertura-integration-test coveralls:report
